spring:
  application:
    name: document-service
  config:
    #import: "optional:classpath:application-secrets.yml"
    import: "optional:file:/app/config/application-secrets.yml"
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 9104
  forward-headers-strategy: framework
  servlet:
    context-path: /
app:
  kafka:
    topic:
      document-uploaded: document-uploaded
  storage:
    type: GCS  # Options: AZURE, GCS
    azure-connection-string: ${AZURE_STORAGE_CONNECTION_STRING:}
    azure-container-name: documents

springdoc:
  api-docs:
    # Expose your OpenAPI JSON at /v3/api-docs
    path: /v3/api-docs
  swagger-ui:
    # Expose Swagger UI at /swagger-ui.html
    path: /swagger-ui
    # Force Swagger UI to use the correct docs URL
    url: /v3/api-docs
    # (Optional) Nice name in the Swagger header
    display-operation-id: true
    doc-expansion: none

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/

logging:
  file:
    name:  # Leave blank so logs go to stdout
  level:
    root: INFO
    za.co.k-polit.comms: DEBUG
  pattern:
    console: '{"document-service - timestamp": "%d{yyyy-MM-dd HH:mm:ss}", "level": "%-5level", "logger": "%logger{36}", "message": "%msg"}%n'