spring:
  application:
    name: document-service
  config:
    import: "optional:classpath:application-secrets.yml"
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 9101
  servlet:
    context-path: /document-service
app:
  storage:
    azure-connection-string: ${AZURE_STORAGE_CONNECTION_STRING:}
    azure-container-name: documents

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/

logging:
  file:
    name:  # Leave blank so logs go to stdout
  level:
    root: INFO
    za.co.k-polit.comms: DEBUG
  pattern:
    console: '{"document-service - timestamp": "%d{yyyy-MM-dd HH:mm:ss}", "level": "%-5level", "logger": "%logger{36}", "message": "%msg"}%n'